### ISSUE TITLE
hyprpm failed to build plugin

### ISSUE THREAD

**Issue by siily-g** [VirtCode/hypr-dynamic-cursors#85]
hi i tried to install this plugin wasnt working for some reason i already did hyprpm update

the output:
hyprpm add https://github.com/virtcode/hypr-dynamic-cursors -v
[v] running version returned: Hyprland 0.49.0 built from branch  at commit 9958d297641b5c84dcff93f9039d80a5ad37ab00  (version: bump to 0.49.0).
Date: Thu May 8 20:15:18 2025
Tag: v0.49.0, commits: 6098
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.7.1
 hyprcursor 0.1.12
 hyprgraphics 0.1.3

no flags were set

[v] parsed commit 9958d297641b5c84dcff93f9039d80a5ad37ab00 at branch  on Thu May 8 20:15:18 2025, commits 6098
✔ adding a new plugin repository from https://github.com/virtcode/hypr-dynamic-cursors
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n]

 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the plugin repos→ Cloning https://github.com/virtcode/hypr-dynamic-cursors
 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the plugin repos✔ cloned
 ━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1 / 5  Cloning the plugin repos✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
→ dynamic-cursors by Virt version
→ Manifest has 16 pins, checking
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Verifying headers[v] installed version returned: Hyprland 0.49.0 built from branch  at commit 9958d297641b5c84dcff93f9039d80a5ad37ab00  (version: bump to 0.49.0).
Date: Thu May 8 20:15:18 2025
Tag: v0.49.0, commits: 6098
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.7.1
 hyprcursor 0.1.12
 hyprgraphics 0.1.3

no flags were set

[v] parsed commit 9958d297641b5c84dcff93f9039d80a5ad37ab00 at branch  on Thu May 8 20:15:18 2025, commits 6098
✔ Hyprland headers OK
→ Building dynamic-cursors
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/sillyg && PKG_CONFIG_PATH="/var/cache/hyprpm/sillyg/headersRoot/share/pkgconfig" make all
mkdir -p out
g++ -shared -Wall --no-gnu-unique -fPIC ./src/cursor.cpp ./src/highres.cpp ./src/main.cpp ./src/config/config.cpp ./src/config/ShapeRule.cpp ./src/mode/ModeRotate.cpp ./src/mode/ModeStretch.cpp ./src/mode/ModeTilt.cpp ./src/mode/utils.cpp ./src/other/Shake.cpp ./src/render/CursorPassElement.cpp ./src/render/renderer.cpp -g `pkg-config --cflags hyprland | awk '{print $NF "/src";}'` `pkg-config --cflags pixman-1 libdrm hyprland` -std=c++26 -o out/dynamic-cursors.so
./src/render/renderer.cpp: In function ‘void renderCursorTextureInternalWithDamage(Hyprutils::Memory::CSharedPointer<CTexture>, Hyprutils::Math::CBox*, const Hyprutils::Math::CRegion&, float, Hyprutils::Math::Vector2D, bool, float, Hyprutils::Math::Vector2D)’:
./src/render/renderer.cpp:67:83: error: ‘class CHyprOpenGLImpl’ has no member named ‘m_monitorTransformEnabled’; did you mean ‘setMonitorTransformEnabled’?
   67 |     const auto TRANSFORM = wlTransformToHyprutils(invertTransform(!g_pHyprOpenGL->m_monitorTransformEnabled ? WL_OUTPUT_TRANSFORM_NORMAL : g_pHyprOpenGL->m_renderData.pMonitor->m_transform));
      |                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                   setMonitorTransformEnabled
make: *** [Makefile:12: out/dynamic-cursors.so] Error 1

✖ Plugin dynamic-cursors failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.

✔ all plugins built
✔ installed repository
✔ you can now enable the plugin(s) with hyprpm enable
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Done!

**Comment by VirtCode** [comment]
Oh right, the last commit broke the build on 0.49.0. Have added a pin so should be fixed now - just try to update again.
