### ISSUE TITLE
[Bug] Error while building after hyprland latest changes

### ISSUE THREAD

**Issue by xBiei** [VirtCode/hypr-dynamic-cursors#119]
The plugin fails to build after https://github.com/hyprwm/Hyprland/commit/920353370bba555010506a1c0b204675c60362fe commit which refactored a lot of stuff, mainly renamings etc..

should be an easy fix.

the errors:
```log
src/main.cpp:65:48: error: ‘CWLSurface’ was not declared in this scope; did you mean ‘Desktop::View::CWLSurface’?
   65 | typedef void (*origSetCursorSurface)(void*, SP<CWLSurface>, const Vector2D&);
      |                                                ^~~~~~~~~~
      |                                                Desktop::View::CWLSurface
```
```
src/main.cpp:67:43: error: ‘CWLSurface’ was not declared in this scope; did you mean ‘Desktop::View::CWLSurface’?
   67 | void hkSetCursorSurface(void* thisptr, SP<CWLSurface> surf, const Vector2D& hotspot) {
      |                                           ^~~~~~~~~~
      |                                           Desktop::View::CWLSurface
```

**Comment by VirtCode** [comment]
thanks for the heads up, should be fixed

**Comment by Tasse500** [comment]
Using NixOS-Unstable, I have a very similar problem. Probably the same issue of refactoring on Hyprland's end?

```
src/render/renderer.cpp:71:51: error: 'invertTransform' was not declared in this scope; did you mean 'Math::invertTransform'?
  71 |     const auto TRANSFORM = wlTransformToHyprutils(invertTransform(!g_pHyprOpenGL->m_monitorTransformEnable…
     |                                                                                          ^~~~~~~~~~~~~~~
     |                                                                                           Math::invertTransform
```

```
src/render/renderer.cpp:71:28: error: 'wlTransformToHyprutils' was not declared in this scope; did you mean 'Math::wlTransformToHyprutils'?
 71 |     const auto TRANSFORM = wlTransformToHyprutils(invertTransform(!g_pHyprOpenGL->m_monitorTransform…
    |                                                   ^~~~~~~~~~~~~~~~~~~~~~
    |                                                    Math::wlTransformToHyprutils
```
