### ISSUE TITLE
Latest commit fails to build with hyprland 48.1

### ISSUE THREAD

**Issue by jaredmontoya** [VirtCode/hypr-dynamic-cursors#71]
```c++
g++ -shared -Wall --no-gnu-unique -fPIC ./src/cursor.cpp ./src/highres.cpp ./src/main.cpp ./src/config/ShapeRule.cpp ./src/config/config.cpp ./src/mode/ModeRotate.cpp ./src/mode/ModeStretch.cpp ./src/mode/ModeTilt.cpp ./src/mode/utils.cpp ./src/other/Shake.cpp ./src/render/CursorPassElement.cpp ./src/render/renderer.cpp -g `pkg-config --cflags hyprland | awk '{print $NF "/src>
./src/render/renderer.cpp: In function 'void renderCursorTextureInternalWithDamage(Hyprutils::Memory::CSharedPointer<CTexture>, Hyprutils::Math::CBox*, const Hyprutils::Math::CRegion&, float, Hyprutils::Math::Vector2D, bool, float, Hyprutils::Math::Vector2D)':
./src/render/renderer.cpp:75:53: error: 'class CHyprOpenGLImpl' has no member named 'm_shaders'
   75 |         case TEXTURE_RGBA: shader = &g_pHyprOpenGL->m_shaders->m_shRGBA; break;
      |                                                     ^~~~~~~~~
./src/render/renderer.cpp:76:53: error: 'class CHyprOpenGLImpl' has no member named 'm_shaders'
   76 |         case TEXTURE_RGBX: shader = &g_pHyprOpenGL->m_shaders->m_shRGBX; break;
      |                                                     ^~~~~~~~~
./src/render/renderer.cpp:77:57: error: 'class CHyprOpenGLImpl' has no member named 'm_shaders'
   77 |         case TEXTURE_EXTERNAL: shader = &g_pHyprOpenGL->m_shaders->m_shEXT; break;
      |                                                         ^~~~~~~~~
make: *** [Makefile:12: out/dynamic-cursors.so] Error 1
```

**Comment by VirtCode** [comment]
Yes, the main branch generally targets the latest `-git` revision of hyprland. However, if you are using hyprpm it should automatically check out the correct version for each hyprland release, which should work. So are you using hyprpm or building yourself?

If you are building yourself, 2e7ea0224d8de63bb3ffead40e44248321b349bc is the latest commit which is still compatible with hl `v0.48.1`. You can also look at the [hyprpm.toml](https://github.com/VirtCode/hypr-dynamic-cursors/blob/main/hyprpm.toml) for other hl versions.

**Comment by jaredmontoya** [comment]
You are right, I chose the wrong commit.
I build myself using a nix package but it's outdated so I override the commit manually. It builds correctly using 2e7ea02
